name: Permission Test

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Test Permissions
        run: |
          echo "Testing repository access"
          mkdir -p test
          echo "Test successful" > test/output.txt
          cat test/output.txt