name: Simple Check

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  check:
    name: Basic Check
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Simple Echo
        run: echo "Hello World"
