name: Test Workflow

on:
  workflow_dispatch:

permissions: # Explicit permissions
  contents: read
  actions: write
  checks: write
  issues: write

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-22.04
    steps:
      - name: Echo Test
        run: echo "This is a test"